---
"$schema": /metaschema-1.json
version: '1.0'
type: object
title: "Product"
description: |
  Schema for defining a product. Products represent software or services
  delivered on the AppSRE Platform. Product declarations include their name,
  description, and responsible owners. This schema enables tracking of product
  metadata and ownership for operational and support purposes.

additionalProperties: false
properties:
  "$schema":
    type: string
    enum:
    - /app-sre/product-1.yml

  labels:
    "$ref": "/common-1.json#/definitions/labels"

  name:
    "$ref": "/common-1.json#/definitions/extendedIdentifier"
    description: |
      The unique name of the product. Used to identify the product across
      the system.

  description:
    type: string
    description: |
      A detailed description of the product, including its purpose and
      any relevant context.

  productOwners:
    type: array
    description: |
      A list of teams or individuals responsible for the running instance
      of the product. Each entry must include a name and email address.
    items:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
          description: |
            The name of the product owner, team, or individual responsible
            for the product.
        email:
          type: string
          format: email
          description: |
            The email address of the product owner for contact and support.
      required:
      - name
      - email

required:
- "$schema"
- labels
- name
- description
- productOwners
