---
"$schema": /metaschema-1.json
version: '1.0'
type: object

additionalProperties: false
properties:
  "$schema":
    type: string
    enum:
    - /openshift/openshift-cluster-manager-environment-1.yml
  labels:
    "$ref": "/common-1.json#/definitions/labels"
  name:
    type: string
  description:
    type: string
  url:
    type: string
    format: uri
  accessTokenClientId:
    type: string
  accessTokenUrl:
    type: string
    format: uri
  accessTokenClientSecret:
    "$ref": "/common-1.json#/definitions/vaultSecret"
required:
- "$schema"
- labels
- name
- url
- description
- accessTokenClientId
- accessTokenUrl
- accessTokenClientSecret
