---
"$schema": /metaschema-1.json
version: '1.0'
type: object
additionalProperties: false
properties:
  "$schema":
    type: string
    enum:
    - /cna/aws-rds-config-1.yml
  vpc:
    "$ref": "/common-1.json#/definitions/crossref"
    "$schemaRef": "/aws/vpc-1.yml"
    description: The VPC the RDS instance is created in.
  db_subnet_group_name:
    type: string
    description: |
      Name of DB subnet group. DB instance will be created in the VPC
      associated with the DB subnet group.
      Must exist in the referenced VPC.
      Mandatory: must be set here or provided via a default.
  instance_class:
    type: string
    enum:
    - db.t2.micro
    - db.t2.small
    - db.t3.small
    - db.m3.medium
    - db.t3.medium
    - db.m4.large
    - db.m4.xlarge
    - db.m4.2xlarge
    - db.m5.large
    - db.m5.xlarge
    - db.m5.2xlarge
    - db.m5.4xlarge
    - db.m5.8xlarge
    - db.m5.12xlarge
    - db.m5.16xlarge
    - db.m5.24xlarge
    - db.m6.large
    - db.m6g.large
    - db.m6g.xlarge
    - db.m6g.2xlarge
    - db.m6g.4xlarge
    - db.m6g.8xlarge
    - db.m6g.12xlarge
    - db.m6g.16xlarge
    - db.r4.large
    - db.r4.xlarge
    - db.r4.2xlarge
    - db.r4.4xlarge
    - db.r4.8xlarge
    - db.r4.16xlarge
    - db.r5.large
    - db.r5.xlarge
    - db.r5.2xlarge
    - db.r5.4xlarge
    - db.r5.8xlarge
    - db.r5.12xlarge
    - db.r5.16xlarge
    - db.r5.24xlarge
    description: |
      Provided via a default or overwritten here.
  allocated_storage:
    type: integer
    description: allocated storage in Gi
  max_allocated_storage:
    type: integer
    description: max allocated storage in Gi
  engine:
    type: string
    enum:
    - postgres
  engine_version:
    type: string
    description: The engine version to use
  major_engine_version:
    type: string
    description: Specifies the major version of the engine that this option group should be associated with
  username:
    type: string
  maintenance_window:
    type: string
    description: |
      The window to perform maintenance in.
      Syntax: 'ddd:hh24:mi-ddd:hh24:mi'. Eg: 'Mon:00:00-Mon:03:00'
  backup_retention_period:
    type: integer
    description: The days to retain backups for
  backup_window:
    type: string
    description: |
      The daily time range (in UTC) during which automated backups are created if they are enabled.
      Example: '09:46-10:16'
      Must not overlap with maintenance_window
  multi_az:
    type: boolean
    description: |
      Whether to use a multi-az configuration that includes a standby instance to improve
      availability when a failover is required (certain upgrades, instance hardware issues, etc.)
  deletion_protection:
    type: boolean
    description:
      Protect against deletion. Defaults to true.
  apply_immediately:
    type: boolean
    description: |
      Indicates whether to apply changes immediately, or wait until the next maintenance window

