---
"$schema": /metaschema-1.json
version: '1.0'
type: object
additionalProperties: false
properties:
  "$schema":
    type: string
    enum:
    - /cna/aws-assume-role-config-1.yml
  slug:
    type: string
required:
- "$schema"
