---
"$schema": /metaschema-1.json
version: '1.0'
type: object
additionalProperties: false
properties:
  "$schema":
    type: string
    enum:
    - /cna/null-asset-config-1.yml
  addr_block:
    type: string
