---
"$schema": /metaschema-1.json
version: '1.0'
type: object

additionalProperties: false
properties:
  "$schema":
    type: string
    enum:
    - /dependencies/dynatrace-environment-1.yml
  name:
    type: string
  description:
    type: string
  environmentUrl:
    description: the URL to a specific Dynatrace entity called environment, which is also known as tenant.
    type: string
  bootstrapToken:
    "$ref": "/common-1.json#/definitions/vaultSecret"
  environment:
    type: string
    enum:
    - integration
    - stage
    - production
  dynatraceRegion:
    type: string
    enum:
    - us-east-virginia
    - eu-west-ireland
    - ap-southeast-singapore
  awsRegion:
    description: a list of HCP AWS regions
    type: array
    items:
      type: string
required:
- "$schema"
- name
- description
- environmentUrl
- bootstrapToken
